### PR TITLE
Msh2nek

### PR DESCRIPTION
**Pull request by nicooff**
Added the converter msh2nek to the tools folder. 

Msh2nek is a Python utility for converting a Fluent mesh (.msh) to a .rea file that can be read by Nek5000. It was initially developed by Mikael Mortensen at University of Oslo. Further modifications were implemented by Jing Gong, Prabal Negi and Ricardo Vinuesa at the Royal Institute of Technology (KTH).

### CODE REVIEW

**Comment by stgeke** [comment]
I really encourage contributions like this!

However, this pull request brings up a general question: Do we want to add all available user contributions to the official project?

I think the answer to this question is yes and no. Yes, if the code meets our standards (whatever that is) and we believe it’s of general interest. This requires a review by an experienced maintainer to see what’s needed for integration.  This can become tedious procedure.

To minimize the effort for sharing contributions, it would be great to have a dedicated area (like a bazar) e.g. a wiki page listing all the contributions including a short description and the link for download. 

What are your thoughts on that?

**Comment by oanaoana** [comment]
I agree that all submissions would clutter the folders in time, however the git was designed with empty folders especially for such future contributions, and tools is a suitable place for mesh converters (as would be 3rd party which stands empty). However since the design was to be an encompass all and not a two repos: main and dependencies there is no other way around it. 

Furthermore the spot for such things used to be on the homepage in meshes. I do not see how the wiki could be referenced properly on the homepage though it could and it should. This submission is similar to the exo2nek and both would fit in the same place.

**Comment by RonRahaman** [comment]
In this case, we had discussed @nicooff 's contribution at our weekly meetings, so many of the core developers had reached a consensus about including it.  @stgeke, I'm sorry that the discussion didn't make it to GitHub for the other off-site developers.

> This requires a review by an experienced maintainer to see what’s needed for integration. This can become tedious procedure.

You're totally right, the approval process can get tedious.  However, I think 3rd-party tools submissions will be relatively infrequent and will not interfere with the functioning of the core code.  Therefore, the necessary discussions shouldn't block overall development.    

> To minimize the effort for sharing contributions, it would be great to have a dedicated area (like a bazar) e.g. a wiki page listing all the contributions including a short description and the link for download.

We do actually have a few pages on the WordPress site for stuff like this ([for example](https://nek5000.mcs.anl.gov/meshes/)).  However, they're really hard to find if you don't know where they are.  Definitely in need of improvement.  

Any ideas about how to make them easier to find?  Maybe this also pertains to this issue: Nek5000/NekDoc#12

**Comment by stgeke** [comment]
Ah ok, didn't know that. Sure, the core-developers decide what to add.

**Pull request merged**
