### PR TITLE
Disabled timers and fixed issue #72

### LINKED ISSUE #72: Bus error due to invalid datatype in dofcnt
Since `ntot2` in `dofcnt` is implicitly declared as an `integer*4`, the call to `i8glsum` can/will (depending on arch.) cause a bus error (the argument is expected to be of type `integer*8`). See backtrace (from a non x86) below,

``` r, engine='bash', count_lines
Process 296370 (nek5000) stopped on signal SIGBUS: Bus error (default) at [i8glsum:1249 ,0x100e9140]
1249  tsum=tsum+a(i)
(dbx) where
>  0 i8glsum(A = (...), N = <illegal>) [".../nek5000/core/math.f":1249, 0x100e9140]
   1 dofcnt() [".../nek5000/core/drive2.f":1578, 0x10030624]
   2 nek_init(intracomm = <illegal>) [".../nek5000/core/drive1.f":152, 0x10027f78]
   3 NEKTON() [".../nek5000/core/drive.f":26, 0x10027b58]
```

### PR DESCRIPTION
**Pull request by stgeke**
- Changed preprocessor symbol NOTIMER to TIMER
- Added a IFPROFILING flag to makenek
- Disabled timing/profiling by default
- Fixed #72
- Removed old mxm files from makefile

### CODE REVIEW

**Comment by stgeke** [comment]
@fischer1 Do you think this PR can be merged?

**Comment by stgeke** [comment]
Fixes #72

**Comment by adampep** [comment]
Is this issue closed? It seems there are some NOTIMER in math.f

**Comment by stgeke** [comment]
@adampep Looks like you are right. Please open up a bug. Thanks!

**Pull request merged**
