### PR TITLE
added characteristics for moving mesh

### PR DESCRIPTION
**Pull request by ananiast**

### CODE REVIEW

**Comment by stgeke** [comment]
Please include a short_test or example ;)

**Comment by stgeke** [comment]
@ananiast The eddy test failed! For more details, see logfile.

**Comment by stgeke** [comment]
@RonRahaman How can I re-run the regression tests?

**Comment by RonRahaman** [comment]
When you go to Travis CI for that build (https://travis-ci.org/Nek5000/Nek5000/builds/173351396), you should be an option to cancel/restart the build.  I just did so myself.  

When you add new commits to the move_char branch, the build should restart automatically, too.

**Pull request merged**
