### PR TITLE
Add generic fld reader

### PR DESCRIPTION
**Pull request by stgeke**

### CODE REVIEW

**Comment by stgeke** [comment]
@hackljf The CMT test failed because I removed lpart. What's the reason you use lpart in CMT?

**Comment by hackljf** [comment]
It's the number of particles for the particle tracking code. I'm removing
it from CMTDATA if you will approve the pull request.

**Comment by stgeke** [comment]
@hackljf How will it work if you remove it?

**Comment by hackljf** [comment]
It will for now. We don't have any cases with particles in short_tests yet

**Comment by hackljf** [comment]
Approve PR 195 and try again. This should not fail anymore

**Pull request merged**
