### PR TITLE
OpenACC setprec_acc on device

### PR DESCRIPTION
**Pull request by RonRahaman**
This implements `setprec_acc` on device.  It allows us to remove the host/device updates surrounding the call to the previous, host-only implmentation of `setprec_acc`.

### CODE REVIEW

**Comment by misunmin** [comment]
This version fails too before going into the first pressure solve.


We can now do testings/correctness checking on summitdev/titan before PR.


________________________________

**Comment by misunmin** [comment]
Same failure on local machine Tesla.


________________________________

**Comment by emerzari** [comment]
Should we revert the commits?

________________________________

**Comment by misunmin** [comment]
Yes

________________________________

**Comment by RonRahaman** [comment]
Okay, I created a PR to revert this one.  I had a version working on tesla, but I must've messed up it up when I merged upstream changes.  

@misunmin, could you let me know how you're doing testing on summitdev and titan?  I'm not really in the loop about that.

**Comment by misunmin** [comment]
We need to revert #423 too. Will reply there.

________________________________

**Pull request merged**
