### PR TITLE
Adding libxsmm support to mxm

### PR DESCRIPTION
**Pull request by maxhutch**
No magic here.  XSMM is the new PP target.

@alheinecke does this interface get the auto-caching?

### CODE REVIEW

**Comment by alheinecke** [comment]
yes, the lastest version of LIBXSMM has the cache for 3 entries.

**Comment by maxhutch** [comment]
This works for me locally.  @RonRahaman have you run buildbot on it?

**Comment by RonRahaman** [comment]
Max, the buildbot completes with the following failed tests.  These are all "expected" failures in develop and seem to be unrelated to your PR.  
- lowMach_test and mhd fail because of bugs in the NekTests.py script.  I've raised issues https://github.com/Nek5000/NekExamples/issues/8 and https://github.com/Nek5000/NekExamples/issues/9).  
- cyl_restart/cb and cyl_restart/pb fail in the master branch.  I'm not sure why.  I'm examining NekTests.py to see if the problems are set up correctly.  
- The remaining ones have failed in the SVN repo for some time now.  I'll mark them as "expected" soon (https://github.com/Nek5000/NekExamples/issues/7)

I'm confident that we can accept this PR.  Do you agree?

CylRestart_Cb.test_PnPn2_Parallel
CylRestart_Cb.test_PnPn2_Serial
CylRestart_Pb.test_PnPn2_Parallel
CylRestart_Pb.test_PnPn2_Serial
Fs2_St1.test_PnPn2_Parallel
Fs2_St1.test_PnPn2_Serial
Fs2_St1.test_PnPn_Parallel
Fs2_St1.test_PnPn_Serial
Fs2_St2.test_PnPn2_Parallel
Fs2_St2.test_PnPn2_Serial
Fs2_St2.test_PnPn_Parallel
Fs2_St2.test_PnPn_Serial
Fs2_StdWv.test_PnPn2_Parallel
Fs2_StdWv.test_PnPn2_Serial
Fs2_StdWv.test_PnPn_Parallel
Fs2_StdWv.test_PnPn_Serial
FsHydro.test_PnPn_Parallel
FsHydro.test_PnPn_Serial
Hemi.test_PnPn_Parallel
Hemi.test_PnPn_Serial
LowMachTest.test_PnPn2_Parallel
LowMachTest.test_PnPn2_Serial
LowMachTest.test_PnPn_Parallel
LowMachTest.test_PnPn_Serial
Mhd_Gpf.test_PnPn_Parallel
Mhd_Gpf.test_PnPn_Serial
Mhd_GpfM.test_PnPn_Parallel
Mhd_GpfM.test_PnPn_Serial
Mhd_GpfB.test_PnPn_Parallel
Mhd_GpfB.test_PnPn_Serial
Os7000.test_PnPn_Parallel
Os7000.test_PnPn_Serial
Peris.test_PnPn_Parallel
Peris.test_PnPn_Serial
Pipe_Helix.test_PnPn_Parallel
Pipe_Helix.test_PnPn_Serial
Rayleigh_Ray1.test_PnPn2_Parallel
Rayleigh_Ray1.test_PnPn2_Serial
Rayleigh_Ray2.test_PnPn2_Parallel
Rayleigh_Ray2.test_PnPn2_Serial
Rayleigh_Ray2.test_PnPn_Parallel
Rayleigh_Ray2.test_PnPn_Serial
Solid.test_PnPn_Parallel
Solid.test_PnPn_Serial
VarVis.test_PnPn_Parallel
VarVis.test_PnPn_Serial

**Comment by maxhutch** [comment]
Sounds good to me.  Thanks for running the tests!

**Comment by RonRahaman** [comment]
Congrats, man!

**Pull request merged**
