### PR TITLE
Add 'int' restart option for interpolation

### PR DESCRIPTION
**Pull request by dshaver14**
calls gfldr for restart when using
`startFrom = case0.f00001 I` 

addresses #415 

currently only supported if param(67) = 6

### CODE REVIEW

**Comment by stgeke** [comment]
Can we have something more descriptive then just 'i' e.g. 'int'.

**Comment by stgeke** [comment]
The CI tests for this PR fail. Please have a look.

**Comment by dshaver14** [comment]
I can add a dummy gfldr subroutine that's defined for NOMPIIO that will fix the EddyUv failed test, but when I try to run  InclDef::test_PnPn_Parallel, I get 

`ABORT: Too many processors (       2) for to few elements (           1).`

This fails with the master branch too. Is this normal? how does this test ever pass at all?

**Comment by yslan** [comment]
The InclDef only has 1 element, so it will fail if you run with 2 processors.

Interestingly, it is set to be compiled with IFMPI=0 and `-DNOMPIIO` 
For other passed test, there are two independent serial jobs launched at the same time.
https://github.com/Nek5000/Nek5000/runs/4998981918?check_suite_focus=true

**Comment by dshaver14** [comment]
So my real issue here is that I assumed the CI tests would be identical to the short_tests. I'll open a separate issue for that. In any case, I expect my changes should pass now.

**Pull request merged**
