### PR TITLE
Rewrite visnek script in bash

### PR DESCRIPTION
**Pull request by paulromano**
I noticed that the visnek script which is referred to in the eddy_uv example in the user's manual is written in tcsh, which is likely not installed by default on most systems. I've change this script from tcsh to bash so that a user doesn't need to install tcsh.

### CODE REVIEW

**Comment by emerzari** [comment]
I think it's preferable to have two separate scripts: the original and one in bash.  Perhaps call it bvisnek ? A lot of our users prefer using other shells other than bash.

**Comment by paulromano** [comment]
To be clear, a user can still have their shell set to tcsh or whatever their favorite shell is -- `visnek` will be able to run so long as bash is installed, and it shouldn't matter to a user that it happened to execute with bash. But, it's your call. If you prefer to have two versions there, I'm happy to add back the tcsh version.

**Comment by emerzari** [comment]
I understand of course. However, users and/or developers may wish to modify or fix logic ... and a lot of them do not use bash.
My preference would be for both to be there.

On Mar 24, 2017, at 10:43 AM, Paul Romano <notifications@github.com<mailto:notifications@github.com>> wrote:


To be clear, a user can still have their shell set to tcsh or whatever their favorite shell is -- visnek will be able to run so long as bash is installed, and it shouldn't matter to a user that it happened to execute with bash. But, it's your call. If you prefer to have two versions there, I'm happy to add back the tcsh version.

**Comment by stgeke** [comment]
I prefer one version - bash. It's installed on almost all systems.

On 24 Mar 2017, at 16:46, emerzari <notifications@github.com <mailto:notifications@github.com> > wrote:

I understand of course. However, users and/or developers may wish to modify or fix logic ... and a lot of them do not use bash.
My preference would be for both to be there.

On Mar 24, 2017, at 10:43 AM, Paul Romano <notifications@github.com <mailto:notifications@github.com> <mailto:notifications@github.com <mailto:notifications@github.com> >> wrote:


To be clear, a user can still have their shell set to tcsh or whatever their favorite shell is -- visnek will be able to run so long as bash is installed, and it shouldn't matter to a user that it happened to execute with bash. But, it's your call. If you prefer to have two versions there, I'm happy to add back the tcsh version.

**Comment by fischer1** [comment]
One version is good...

Paul

________________________________

**Comment by emerzari** [comment]
Ok.

________________________________

**Comment by RonRahaman** [comment]
If you're really concerned about shell versions, you can write it portably so one can use #!/bin/sh.  visnek doesn't do anything in bash or tsch that can't be done in just /bin/sh

**Comment by paulromano** [comment]
@RonRahaman I was actually just thinking that too.

**Comment by paulromano** [comment]
OK, just made a commit which makes `visnek` a POSIX compliant shell script. I also fixed some markdown errors in README.md.

**Comment by RonRahaman** [comment]
@paulromano , I think this looks great.  I confirmed that it works in Ubuntu, where /bin/sh points to the [dash](http://manpages.ubuntu.com/manpages/xenial/man1/dash.1.html) shell.  I think dash is the most minimal POSIX-compliant shell that I easily have access to.  

@emerzari, @stgeke, does this satisfy you.

**Comment by emerzari** [comment]
It's good with me. I haven't tested it on all variations of cases though.

On Mar 25, 2017, at 10:00 AM, Ron Rahaman <notifications@github.com<mailto:notifications@github.com>> wrote:


@paulromano<https://github.com/paulromano> , I think this looks great. I confirmed that it works in Ubuntu, where /bin/sh points to the dash<http://manpages.ubuntu.com/manpages/xenial/man1/dash.1.html> shell. I think dash is the most minimal POSIX-compliant shell that I easily have access to.

@emerzari<https://github.com/emerzari>, @stgeke<https://github.com/stgeke>, does this satisfy you.

**Comment by stgeke** [comment]
I don't want to approve it as I am not familiar with it. Who is willing to review/approve it?

On 25 Mar 2017, at 16:23, emerzari <notifications@github.com <mailto:notifications@github.com> > wrote:

It's good with me. I haven't tested it on all variations of cases though.

On Mar 25, 2017, at 10:00 AM, Ron Rahaman <notifications@github.com <mailto:notifications@github.com> <mailto:notifications@github.com <mailto:notifications@github.com> >> wrote:


@paulromano<https://github.com/paulromano> , I think this looks great. I confirmed that it works in Ubuntu, where /bin/sh points to the dash<http://manpages.ubuntu.com/manpages/xenial/man1/dash.1.html <http://manpages.ubuntu.com/manpages/xenial/man1/dash.1.html> > shell. I think dash is the most minimal POSIX-compliant shell that I easily have access to.

@emerzari<https://github.com/emerzari>, @stgeke<https://github.com/stgeke>, does this satisfy you.

**Comment by RonRahaman** [comment]
It looks good to me.  @paulromano did a careful job of translating the shell script, so there shouldn't be any subtle bugs in it.

**Pull request merged**
