### PR TITLE
quick fix  to ms_glsc2 declaration in PARALLEL

### PR DESCRIPTION
**Pull request by kmittal2**
just a quick fix in PARALLEL.. don't need to change function declaration in math.f because each function includes PARALLEL through TOTAL.

### CODE REVIEW

**Comment by stgeke** [comment]
I prefer correct declarations.

On 5 Sep 2018, at 23:06, k10 <notifications@github.com <mailto:notifications@github.com> > wrote:

just a quick fix in PARALLEL.. don't need to change function declaration in math.f because each function includes PARALLEL through TOTAL.

--------------------------------

You can view, comment on, or merge this pull request online at:

  https://github.com/Nek5000/Nek5000/pull/531


Commit Summary 
*	fix ms_glsc2

File Changes 
*	 M core/PARALLEL (2) 

Patch Links: 
*	https://github.com/Nek5000/Nek5000/pull/531.patch 
*	https://github.com/Nek5000/Nek5000/pull/531.diff

**Comment by kmittal2** [comment]
That seems to require that the user declare ms_glsc2 as real in the subroutine that they want to call it in as well.. I think we should avoid it.
Even if we include this in Parallel, we will have to assume that the user has included Parallel in the subroutine that they are calling ms_glsc2 from. To avoid this, should we consider renaming these functions such that they don't default to integers?

**Comment by pschlatt1** [comment]
I think it is quite dangerous to have in a code where the typical user does not use IMPLICIT NONE non-integers that default to integers. I would definitely recommend renaming (which then of course means that prefixes are not a good solution as they might be used for all types to variables.)

**Comment by stgeke** [comment]
We need to explicitly define all functions anyway to support IMPLICIT NONE in .usr files. For best visibitly I prefer to do this through SIZE. This way we're safe and renaming is not needed.

-----Original message-----

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/Nek5000/commit/597cdbccd56496dfaf3a725e5598b0e4c3406067

**Pull request closed without merging**
