### PR TITLE
Fix for different ps solvers

### PR DESCRIPTION
**Pull request by stgeke**

### CODE REVIEW

**Comment by stgeke** [comment]
Just realized, that I forgot to commit some other files. Please don't merge yet.

**Comment by stgeke** [comment]
@RonRahaman Is there a way to see the conflicts?

**Comment by RonRahaman** [comment]
Yes, you have to resolve conflicts locally.  In this case, you'll have to merge Nek5000:release/v16.0.0 into stgeke:par_impv on your local copy, then push back to your remote copy.  This PR should be updated.

**Comment by stgeke** [comment]
@fischer1 Can you do a review and merge the changes if you think they are ok.

**Pull request merged**
