### PR TITLE
Added minimal set of files for short_tests

### PR DESCRIPTION
**Pull request by RonRahaman**
This adds MOST OF the test cases mentioned by @stgeke in Issue #28.  Several were omitted for the following reasons:
- These tests exceeded the maximum time limit for Travis jobs:
  - benard/ray_dd.rea PN-PN serial
  - benard/ray_dn.rea PN-PN serial
  - benard/ray_nn.rea PN-PN serial
  - benard/ray_nn.rea PN-PN-2 serial
  - eddy/eddy_uv.rea PN-PN parallel
  - eddy/eddy_uv.rea PN-PN-2 parallel
- For these tests, the stdout exceeded Travis' limit for log output
  - var_vis/st2.rea

Additionally, I have omitted Docker from the toolchain.  I actually feel pretty strongly about this.  Without Docker, the .travis.yml is much easier to understand, and I believe the other Nek developers will be able to maintain it with much less effort.  Furthermore, the Travis results are much more intelligible.

### CODE REVIEW

**Comment by stgeke** [comment]
I think we can remove `var_vis`. The test is useless at the moment.
Can we add mv_cyl from the examples? It's important for the lowMach number stuff but it requires a 3rd-party ODE solver (CVODE).

**Comment by stgeke** [comment]
LowMach requires PnPn. So it doesn't make sense to run `LowMachTest::test_PnPn2_Serial` and `LowMachTest::test_PnPn2_Parallel`.

**Comment by RonRahaman** [comment]
The legacy test suite didn't run mv_cyl.  I'd be happy to add a new test, if you can provide some guidance.

The tests suite does roughly the following
1. Tweak the parameters SIZE and .rea files, depending on the formulation
2. Compile and run the example
3. Grep stdout for some value(s)
4. Compare the value(s) to established reference value(s) +/- some tolerance

I don't have the expertise to:
1. Decide which parameters should be set the SIZE/.rea files
2. Decide which values to search in stdout
3. Decide reference values +/- tolerance

If you can provide guidance for those items, it's easy to actually implement the test

**Comment by stgeke** [comment]
I was more concerned about CVODE but I guess it's not a big deal. We just need to build it from the source within the test. Will do it myself. It's a good exercise for me to become familiar with the new system ;)

**Comment by RonRahaman** [comment]
> LowMach requires PnPn. So it doesn't make sense to run LowMachTest::test_PnPn2_Serial and LowMachTest::test_PnPn2_Parallel.

I'm glad you mentioned that.  LowMachTest::test_PnPn2_\* actually tests to see if the simulation aborts.  That is, the test case greps for the phrase: "ABORT: For lowMach," in stdout and reports success if that phrase was found.  A few other test cases are evaluated this way as well.  

However, for several months, these test cases have NOT aborted as expected:
- `fs_2/st1.rea`, PnPn
- `fs_2/std_wv.rea`, PnPn
- `fs_hydro/fs_hydro.rea``, PnPn
- `peris/peris.rea`, PnPn
- `solid/solid.rea`, PnPn
- `var_vis/var_vis.rea`, PnPn

Just to be clear: **these tests are expected to abort, but they do not abort in the current version of Nek5000.**

This is a problem that @fischer1 wanted to address.  He suspected that he and Ananias had unintentionally short-circuited some error checks that you had in place.  Any thoughts?

**Comment by stgeke** [comment]
We added all the missing bits (stress formulation, moving mesh, varying viscosity) to the PnPn solver. These test are expected not to abort anymore! Only lowMach with PnPn2 should abort.

**Comment by RonRahaman** [comment]
Oh, fantastic.  So how do we establish reference solutions for those PnPn test cases?

Here are the references solutions for the corresponding PnPn-2 test cases:

| Test case | Variable | Timestep | Reference value | Tolerance |
| --- | --- | --- | --- | --- |
| fs_2/st1 | gmres | 1.00E+00 | 0.00000E+00 | 3.80E+01 |
| fs_2/st1 | amp | 2.00E+02 | 6.38241E-01 | 1.00E-06 |
| fs_2/std_wv | gmres | 1.00E+00 | 0.00000E+00 | 2.00E+01 |
| fs_2/st1 | amp | 2.00E+02 | 1.40329E-01 | 1.00E-06 |
| fs_hydro | gmres | 1.00E+00 | 0.00000E+00 | 1.08E+02 |
| fs_hydro | AMP | 1.00E+03 | -6.46165E-05 | 2.00E-03 |
| peris | gmres | 1.00E+00 | 0.00000E+00 | 1.80E+01 |
| solid | error | final | 7.82123E-05 | 1.00E-06 |
| var_vis | gmres | final | 0.00000E+00 | 1.90E+01 |

**Pull request merged**
