### PR TITLE
Adding missing PARDICT names to make it consistent with uparam length

### PR DESCRIPTION
**Pull request by adampep**

### CODE REVIEW

**Comment by adampep** [comment]
something wrong with communication with travis as all the test seem to be finished

**Comment by stgeke** [comment]
Do we really need 20 user parameters instead of just 10?

**Comment by adampep** [comment]
Depends on the user. I didn't set size of uparam. It was set to 20 and is kept this way (all the initialisation loops) through the code. Only PARDICT was inconsistent setting 10 instead of 20 names.

**Comment by stgeke** [comment]
I think we are ok as long as PARDICT is using a smaller number. For now I don't see the need to expose 20 user parameters.

**Comment by adampep** [comment]
OK. Anyhow size of uparam in INPUT can be misleading. What would be the goal to keep space in uparam that cannot be set in parameter file?

**Comment by ggiannako** [comment]
Since the space is there, I would be happy if there was support for more than 10 uparams by default. Thus I do not have to modify the source (or use another file) every time I need them (more and more often lately in my simulations).

**Comment by stgeke** [comment]
Ok, lets use `luparam` in the code and set it to 20 in `INPUT`.

**Comment by stgeke** [comment]
btw: There are also other ways to define case specific parameters. You could use `#DEFINE` or use ini-reader to read your (user specific) section in the .par file.

**Comment by adampep** [comment]
I do it in my code. It was mostly for consistency reason. Do you want to rename uparam to luparam?

**Comment by stgeke** [comment]
No I just want to use luparam instead of a hardwired size (e.g. 20) in the code. Sure this won't work in PARDICT.

On 25 Aug 2017, at 14:50, Adam Peplinski <notifications@github.com <mailto:notifications@github.com> > wrote:

I do it in my code. It was mostly for consistency reason. Do you want to rename uparam to luparam?

**Pull request closed without merging**
