### PR TITLE
Improved re2 workflow

### PR DESCRIPTION
**Pull request by thilinarmtb**
### TODO

- [x] Add periodic mesh support
- [x] Fix test failures with the map files
- [x] Fix test failures of 2D meshes
- [ ] Use proper formatting to print read/transfer times
- [ ] Cleanup the git history

### CODE REVIEW

**Comment by stgeke** [comment]
Can you please fix the merge conflicts and ensure that this PR works as expected with the latest master.

**Comment by thilinarmtb** [comment]
> Can you please fix the merge conflicts and ensure that this PR works as expected with the latest master.

Will do.

**Comment by thilinarmtb** [comment]
Seems like `FsHydro` and `InclDef` fails in master as well. I will check why `IO_Test fails.

**Comment by stgeke** [comment]
The two failed before. Will push a fix soon. The I/O test is a different story.

**Comment by stgeke** [comment]
Please change to the new reader nek_file_open + nek_file_read which we introduced recently. You still seem to use byte_open etc.

**Comment by stgeke** [comment]
It would be great if you could merge this PR soon. Can you please implement the required changes.

**Comment by stgeke** [comment]
This PR is complete and out dated. Closing it for now. Feel free to reopen it.

**Pull request closed without merging**
