### PR TITLE
Assign BCs in par

### PR DESCRIPTION
**Pull request by dshaver14**
Adds the 'boundaryTypeMap' key for '[Velocity]', '[Temperature]', and '[Scalar]' tokens. Also adds the optional 'boundaryIDMap' for '[Mesh]' for the case on non-sequential sideset IDs. This also handles error checking for an inconsistent number of IDs, unsupported BC types, and too many specified BCs.

e.g. for custom sideset IDs:

```
[MESH]
boundaryIDMap = 20, 10, 30

[VELOCITY]
boundaryTypeMap = outlet, inlet, wall
```

for sequential IDs:

```
[MESH]
boundaryIDMap = 1, 2, 3

[VELOCITY]
boundaryTypeMap = inlet, outlet, wall
```

is equivalent to 

```
[MESH]

[VELOCITY]
boundaryTypeMap = inlet, outlet, wall
```

Or the three-character codes can be used directly:

```
[MESH]
boundaryIDMap = 10, 20, 30

[VELOCITY]
boundaryTypeMap = v  ,O  ,W  
```

### CODE REVIEW

**Comment by stgeke** [comment]
Is `boundaryIDMap` in MESH optional or mandatory? If the IDs are sequential I don't see any need to specify them explicitly.

**Comment by stgeke** [comment]
Ahh I see in the description you say it's optional so please ignore my question/comment.

**Comment by emerzari** [comment]
It would be n ice to include a test for this ?

**Comment by dshaver14** [comment]
This now properly handles extra blank BCs, in case for some reason your mesh is missing Boundary 2 you could do:

```
[MESH]
boundaryIDMap = 1, 3, 4

[VELOCITY] 
boundaryTypeMap= inlet, outlet, wall
```

or simply

```
[MESH]

[VELOCITY]
boundaryTypeMap = inlet, none, outlet, wall
```

It still throws an error for unused boundary types other than "`   `" or "none"

**Comment by stgeke** [comment]
Can you please add some CI testing for this feature.

**Comment by stgeke** [comment]
We can merge this PR if you add some CI coverage.

**Comment by dshaver14** [comment]
This adds a basic CI test to count the number of BCs assigned in the cbc array. I will add another to make sure it's working with CHT as well. 

I also added the implicit source term test to the CI suite.

Incidentally, this also address #630.

**Comment by dshaver14** [comment]
The CHT test is only for 2D, but I think it's good enough for now. 

I would appreciate if someone could look over BCDICT for any 3 character boundary codes I missed.

**Comment by stgeke** [comment]
Please fix the merge conflicts.
Is this ready to be merged?

**Comment by dshaver14** [comment]
It's ready to be merged.

**Comment by stgeke** [comment]
Let's remove the changes for https://github.com/Nek5000/Nek5000/issues/630 from this PR. One PR at the time.

**Comment by dshaver14** [comment]
The BCs need to be printed to the log file for the new CI tests. I would also have to separate those.

**Pull request merged**
