### PR TITLE
Exact pressure solution

### PR DESCRIPTION
**Pull request by kent0**
Added a exactp subroutine that calculates the exact pressure for the eddy case. In userchk, the pressure error gets written with the 'P err' string identifier. I'm not sure whether I should prescribe the exact pressure in useric, so please give me some guidance on that matter.

### CODE REVIEW

**Comment by kent0** [comment]
I ran the eddy case with nekb as a check, but I now realize that I should've ran the short_tests as well. I'll figure out the issue and push the changes.

**Comment by RonRahaman** [comment]
@kentokaneko, do you have Travis linked to your fork of Nek5000?  

Travis can automatically run the same regression tests on your fork, so you don't get any nasty surprises when you make a PR.  To set it up, follow steps 1 and 2 [here](https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A).

**Comment by kent0** [comment]
@RonRahaman No, I don't have that setup yet. Thanks for the tip

**Comment by stgeke** [comment]
What is the motivation for this pull request?

**Comment by fischer1** [comment]
Since we have an exact pressure solution as well as velocity, we should use it --- it's helpful in comparing methods in the future.  Some have better pressure approximations than others.

**Comment by kent0** [comment]
Currently, the pressure error gets written out, but it's not being checked in the test. I will add that functionality

**Comment by kent0** [comment]
The pressure tests have been added, I believe this branch is good to go.

**Pull request merged**
