### PR TITLE
CMT-nek updates for forces and restarts

### PR DESCRIPTION
**Pull request by hackljf**
nekuic was initializing bx, by and bz for ldimt > 3, npscal=0 independently of IFMHD. This was writing outside of bx's bounds when lbelt=1, which represents a CMT-nek use case. This PR only initializes bx IFMHD.

### CODE REVIEW

**Comment by stgeke** [comment]
You PR includes many other (unrelated) changes. Please separate them.

I don't understand your changes to `ic.f`:

nekuic() is called for ifield=1,nfield where nfield is typically (ifmhd=.f.) 2+NPSCAL
we access bx,by,bz arrays only if ifield == ifldmhd = 3+NSPCAL

Can you please explain the rational for your "fix".

**Comment by hackljf** [comment]
I use the T array for diagnostic scratch space for the artificial viscosity
method. I run with ldimt=6, so nfield typically exceeds ifldmhd even though
ifmhd=.false. and npscal=0.

**Comment by stgeke** [comment]
I see. Can you please add a new pull request containing just the chance in ic.f.
Thanks!

**Comment by hackljf** [comment]
Done. Please excuse the patch-2 branch.

**Pull request merged**
