### PR TITLE
update readme files, and add CHT to gmsh2nek

### PR DESCRIPTION
**Pull request by yhaomin2007**

### CODE REVIEW

**Comment by stgeke** [comment]
Why does this PR touch many more file than just the readme?

**Comment by yhaomin2007** [comment]
All commits except the last one are made for the previous pull request, which is already merged. Only the last commit is for this pull request.

**Comment by stgeke** [comment]
The PR should only change the readme.

**Comment by yhaomin2007** [comment]
Yes, i know. but the CHT feature in gmsh2nek is also request by some users.

**Pull request closed without merging**
