### PR TITLE
Number of saved restart files consistent with time integration order.

### PR DESCRIPTION
**Pull request by EvelynOtero**

### CODE REVIEW

**Comment by stgeke** [comment]
Please include the modified example in your pull request.

**Comment by stgeke** [comment]
Fixes #131

**Comment by EvelynOtero** [comment]
What do you mean by including example in pull request? An example for multiple files restart exists in NekExamples and is not part of Nek5000 repository, so the current pull request contains changes to the nek core only.

**Comment by RonRahaman** [comment]
Thanks for fixing this, @EvelynOtero.   We'll merge this PR as well as your fixes to cyl_restart in NekExamples (https://github.com/Nek5000/NekExamples/pull/28).  

We won't add cyl_restart to short_tests, since we haven't establshed informative test criteria for it.  Hence, you won't see it tested in Travis (the automated testing framework for pull requests, which appears here on GitHub).   If you have some ideas about informative criteria, we can talk offline.  

After this merge, cyl_restart will still be run by Jenkins (the automated testing framework for merges).  Jenkins runs the latest build of Nek5000 with all of NekExamples, including your latest fixes from https://github.com/Nek5000/NekExamples/pull/28.  Our Jenkins servers aren't integrated with GitHub (yet!) but I can email you a link and keep you posted on the status.

**Comment by EvelynOtero** [comment]
Thanks @RonRahaman! It is fine like this.

**Pull request merged**
