### PR TITLE
update readme files of gmsh2nek and exo2nek. and add CHT feature to gmsh2nek

### PR DESCRIPTION
**Pull request by yhaomin2007**
…msh2nek

### CODE REVIEW

**Comment by yhaomin2007** [comment]
I did a new pull request, and it has no conflict with current version. Thanks.

**Comment by dshaver14** [comment]
@yhaomin2007 , can you provide me with sample .msh and .exo files to test the CHT capabilities? As simple as possible would be nice, I'd like to also use them to setup a test for #787

**Comment by yhaomin2007** [comment]
will do. thanks.

**Comment by yhaomin2007** [comment]
how about tube+shell ?

**Comment by stgeke** [comment]
@dshaver-ANL What's missing to merge this PR?

**Review by dshaver14 — APPROVED** [review]
Ready to merge

**Pull request merged**
