### PR TITLE
Serial AMG setup using Hypre (Issue-205)

### PR DESCRIPTION
**Pull request by nicooff**
A serial version of the AMG setup using Hypre can be found in tools/amg_hypre.

### CODE REVIEW

**Comment by stgeke** [comment]
I recommend two small changes:
Can you change the makefile to make it compatible with maketools. Please modify `tools/makefile` such that this tool does not get compiled by default (similiar to exo2nek). Otherwise maketools will fail if Hypre is not installed.

**Comment by nicooff** [comment]
I fixed maketools and added CFLAGS_IN to the amg_hype/makefile. And no more capital letter to makefile.  Are these changes sufficient?

**Comment by stgeke** [comment]
Not really as the makefile is should use the maketools variables (CC, LFLAGS_IN, ...). Not a big deal, I can take care of this. 

Why is code using MPI if only one rank is supported?

**Comment by stgeke** [comment]
Merged in #209

**Comment by nicooff** [comment]
Thanks!

The Hypre library requires MPI. I am currently not using the parallel features because of matrix partitioning and because the smoother is only serial for the moment.

**Comment by stgeke** [comment]
You can build HYPRE w/o MPI.

On 31 Jan 2017, at 10:51, Nicolas <notifications@github.com <mailto:notifications@github.com> > wrote:

Thanks!

The Hypre library requires MPI. I am currently not using the parallel features because of matrix partitioning and because the smoother is only serial for the moment.

**Comment by nicooff** [comment]
Right. Thank you.

**Pull request closed without merging**
