### PR TITLE
WIP: Refactor makenek for faster builds

### PR DESCRIPTION
**Pull request by stgeke**
- Make AMG a runtime flag
- Compile JL stuff only once

### CODE REVIEW

**Comment by stgeke** [comment]
@RonRahaman I don't use boolean variables in `makenek` anymore, as they are not well supported in bash. Can please change the CI Python scripts accordingly.

**Comment by RonRahaman** [comment]
@stgeke, sure I will fix that accordingly.  On a related note:  When you use a flag in makenek (like MPI, PROFILING, VISIT), you interpret 0 as "false" and 1 as "true".  Could you interpret 0 as "false" and any non-zero as "true"?  That's convention in most programming languages.

**Comment by RonRahaman** [comment]
I have some pretty fundamental issues with this PR.  In particular, the makefiles are still much longer than they need to be.  In particular, you aren't making use of pattern rules where there are some very reasonable uses for them.  

For example, I wrote this a while back (see below).   It builds both nek5000 and jl in 102 lines.  It also uses the standard GNU make compiler flags (CFLAGS, CPPFLAGS, FFLAGS, etc.)

I guess my point is this.  Your new makefiles are still a big improvement.  However, while we're on the issue of improving the makefiles, there's a lot more that we can do.  

``` make
# == Source and destination directories ============================================================
VPATH    = @srcdir@/Nek5000/core:@srcdir@/Nek5000/core/cmt:@srcdir@/Nek5000/core/3rd_party:@srcdir@/Nek5000/jl
srcdir   = @srcdir@
builddir = @builddir@
objdir   = @builddir@/obj
includedir = @builddir@/include

# == Standard GNU Compilers and flags ==============================================================
CC       = @CC@
CFLAGS   = @CFLAGS@
CPPFLAGS = @CPPFLAGS@ @DEFS@ \
           -I$(builddir) -I$(includedir) -I$(srcdir)/Nek5000/core -I$(srcdir)/Nek5000/core/cmt \
           -I$(srcdir)/Nek5000/core/3rd_party -I$(srcdir)/Nek5000/jl
LDFLAGS  = @LDFLAGS@
LIBS     = @LIBS@

F77      = @F77@
FFLAGS   = @FFLAGS@ @FCFLAGS_f@ $(subst -D, @FC_DEFINE@, @DEFS@) \
           -I$(builddir) -I$(includedir) -I$(srcdir)/Nek5000/core -I$(srcdir)/Nek5000/core/cmt \
           -I$(srcdir)/Nek5000/core/3rd_party -I$(srcdir)/Nek5000/jl
FLIBS    = @FLIBS@

# == Nek-only compilers and flags ==================================================================
nek_debug_flags = @nek_debug_flags@
nek_opt_flags   = @nek_opt_flags@
nek_real8_flags = @nek_real8_flags@
jl_prefix       = @jl_prefix@

# == FORTRAN objects ===============================================================================
nek_drive_obj  = $(addprefix $(objdir)/, drive.o)

nek_core_f_obj = $(addprefix $(objdir)/, \
                 drive1.o drive2.o plan4.o bdry.o coef.o conduct.o connect1.o connect2.o \
                 dssum.o edgec.o eigsolv.o gauss.o genxyz.o navier1.o makeq.o navier0.o \
                 navier2.o navier3.o navier4.o prepost.o speclib.o map2.o turb.o mvmesh.o ic.o \
                 ssolv.o planx.o mxm_wrapper.o hmholtz.o gfdm_par.o  gfdm_op.o gfdm_solve.o \
                 subs1.o subs2.o genbox.o gmres.o hsmg.o convect.o induct.o perturb.o navier5.o \
                 navier6.o navier7.o navier8.o fast3d.o fasts.o calcz.o byte_mpi.o postpro.o \
                 cvode_driver.o vprops.o qthermal.o cvode_aux.o makeq_aux.o papi.o nek_in_situ.o \
                 readat_new.o @CASENAME@.o)

nek_math_obj   = $(addprefix $(objdir)/, math.o)
nek_blas_obj   = $(addprefix $(objdir)/, @nek_blas_obj@)   # blas.o | null
nek_cmt_obj    = $(addprefix $(objdir)/, @nek_cmt_obj@)    # drive1_cmt.o ... | cmt_dummy.o
nek_lapack_obj = $(addprefix $(objdir)/, @nek_lapack_obj@) # dsygv.o ssygv.o | null
nek_mpi_obj    = $(addprefix $(objdir)/, @nek_mpi_obj@)    # byte_mpi.o comm_mpi.o | byte_mpi.o comm_mpi.o mpi_dummy.o
nek_mxm_obj    = $(addprefix $(objdir)/, @nek_mxm_obj@)    # mxm_std.o | mxm_std.o mxm_bgq.o
nek_neknek_obj = $(addprefix $(objdir)/, @nek_neknek_obj@) # singlmesh.o | multimesh.o

nek_flib_obj   = $(nek_core_f_obj) $(nek_math_obj) $(nek_blas_obj) $(nek_cmt_obj) \
                 $(nek_lapack_obj) $(nek_mpi_obj) $(nek_mxm_obj) $(nek_neknek_obj)

# == C objects =====================================================================================
nek_core_c_obj = $(addprefix $(objdir)/, \
                 byte.o chelpers.o nek_comm.o finiparser.o iniparser.o dictionary.o)

jl_core_obj    = $(addprefix $(objdir)/$(jl_prefix), \
                 gs.o sort.o sarray_transfer.o sarray_sort.o gs_local.o crystal.o comm.o tensor.o \
                 fail.o fcrystal.o)
jl_interp_obj  = $(addprefix $(objdir)/$(jl_prefix), \
                 findpts.o findpts_local.o obbox.o poly.o lob_bnd.o findpts_el_3.o findpts_el_2.o)
jl_cgs_obj     = $(addprefix $(objdir)/$(jl_prefix), @jl_cgs_obj@)

nek_clib_obj   = $(nek_core_c_obj) $(jl_core_obj) $(jl_interp_obj) $(jl_cgs_obj)

# == Rules =========================================================================================
nek5000: $(nek_drive_obj) $(nek_flib_obj) $(nek_clib_obj)
	$(F77) -o $@ $(nek_drive_obj) $(nek_flib_obj) $(nek_clib_obj) $(LDFLAGS) $(LIBS) $(FLIBS)
	@size nek5000

$(nek_drive_obj) $(nek_core_f_obj) $(nek_cmt_obj): $(objdir)/%.o: %.f SIZE | $(objdir)
	$(F77) -c $(FFLAGS) $(nek_opt_flags) $(nek_debug_flags) $(nek_real8_flags) $< -o $@

$(nek_mpi_obj) $(nek_neknek_obj): $(objdir)/%.o: %.f SIZE mpiheader | $(objdir)
	$(F77) -c $(FFLAGS) $(nek_opt_flags) $(nek_debug_flags) $(nek_real8_flags) $< -o $@

$(nek_math_obj) $(nek_mxm_obj): $(objdir)/%.o : %.f SIZE | $(objdir)
	$(F77) -c $(FFLAGS) -O3 $(nek_debug_flags) $(nek_real8_flags) $< -o $@

$(nek_blas_obj) $(nek_lapack_obj): $(objdir)/%.o: %.f SIZE | $(objdir)
	$(F77) -c $(FFLAGS) -O0 $(nek_debug_flags) $< -o $@

$(nek_core_c_obj): $(objdir)/%.o: %.c | $(objdir)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $(nek_opt_flags) $(nek_debug_flags) $< -o $@

$(jl_core_obj) $(jl_interp_obj) $(jl_cgs_obj): $(objdir)/$(jl_prefix)%.o: %.c | $(objdir)
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $(nek_opt_flags) $(nek_debug_flags) $< -o $@

mpiheader: | $(includedir)
ifneq ($(findstring mpi_dummy.o, $(nek_mpi_obj)),)
	cp $(srcdir)/Nek5000/core/mpi_dummy.h $(includedir)/mpif.h
else
	rm -rf $(srcdir)/Nek5000/core/mpif.h $(includedir)/mpif.h
endif

$(objdir) $(includedir):
	mkdir -p $@

clean:
	rm -rf nek5000 $(nek_drive_obj) $(nek_flib_obj) $(nek_clib_obj) $(srcdir)/Nek5000/core/mpif.h $(includedir)/mpif.h

.PHONY: mpiheader clean
```

**Comment by RonRahaman** [comment]
@stgeke, I submitted a PR to your branch that should fix the failing CI tests ( https://github.com/stgeke/Nek5000/pull/3 ).  Once you approve that PR, the changes will appear here.

**Comment by stgeke** [comment]
I agree. Just took what already existed and improved on some (for sure) not all fronts. My focus was functionality not beauty ;)

I am not done with this PR. Feel free to push your improvements on top of it when I am ready.

**Comment by fischer1** [comment]
There are very good reasons why the makefile is long and not compact.

Over the decades, we have encountered optimizations that led to failure for certain routines on certain
platforms.

That's why optimization is set differently for each routine.

The length of the makefile cannot possibly matter....


________________________________

**Comment by stgeke** [comment]
@RonRahaman Any idea why get undefined references all of the sudden?

**Comment by RonRahaman** [comment]
Yes, looks as if the compile line for the JL objects is now wrong.  In particular, it's not including the headers in Nek5000/jl.  In this PR, the compile line is:
```
gcc -g -O2 -DUNDERSCORE -DPREFIX=jl_ -DGLOBAL_LONG_LONG  -c findpts_el_2.c -o findpts_el_2.o
```
But in the master branch, it's something like this:
```
gcc -c  -O2  -DNOMPIIO -DUNDERSCORE -DTIMER -DGLOBAL_LONG_LONG -I/home/travis/build/Nek5000/Nek5000/jl -DPREFIX=jl_ /home/travis/build/Nek5000/Nek5000/jl/findpts_el_2.c -o obj/jl_findpts_el_2.o
```

**Comment by stgeke** [comment]
Good catch. Thanks!

On 28 Mar 2017, at 17:53, Ron Rahaman <notifications@github.com <mailto:notifications@github.com> > wrote:

Yes, looks as if the compile line for the JL objects is now wrong. In particular, it's not including the headers in Nek5000/jl. In this PR, the compile line is:


gcc -g -O2 -DUNDERSCORE -DPREFIX=jl_ -DGLOBAL_LONG_LONG  -c findpts_el_2.c -o findpts_el_2.o


But in the master branch, it's something like this:


gcc -c  -O2  -DNOMPIIO -DUNDERSCORE -DTIMER -DGLOBAL_LONG_LONG -I/home/travis/build/Nek5000/Nek5000/jl -DPREFIX=jl_ /home/travis/build/Nek5000/Nek5000/jl/findpts_el_2.c -o obj/jl_findpts_el_2.o

**Comment by stgeke** [comment]
Well actually the "missing" flags are not needed. The include is not needed as the files are in the same dir. The other preprocessor symbol are for the Fortran part. 

It compiles fine on my box. Strange!

On 28 Mar 2017, at 18:25, Stefan K. <notifications@github.com <mailto:notifications@github.com> > wrote:

Good catch. Thanks!

On 28 Mar 2017, at 17:53, Ron Rahaman <notifications@github.com <mailto:notifications@github.com> <mailto:notifications@github.com <mailto:notifications@github.com> > > wrote:

Yes, looks as if the compile line for the JL objects is now wrong. In particular, it's not including the headers in Nek5000/jl. In this PR, the compile line is:


gcc -g -O2 -DUNDERSCORE -DPREFIX=jl_ -DGLOBAL_LONG_LONG -c findpts_el_2.c -o findpts_el_2.o


But in the master branch, it's something like this:


gcc -c -O2 -DNOMPIIO -DUNDERSCORE -DTIMER -DGLOBAL_LONG_LONG -I/home/travis/build/Nek5000/Nek5000/jl -DPREFIX=jl_ /home/travis/build/Nek5000/Nek5000/jl/findpts_el_2.c -o obj/jl_findpts_el_2.o

**Pull request closed without merging**
