### PR TITLE
Add some fixes for 2B element support

### PR DESCRIPTION
**Pull request by stgeke**
Replaces https://github.com/Nek5000/Nek5000/pull/767

### CODE REVIEW

**Review by misunmin — COMMENTED** [review]
To be consistent within reader_re2.f: character*132 hdr, we might do
        write (6,'(a,a132)') ' hdr:', hdr
while map2.f is ok with a80?

**Comment by stgeke** [comment]
The header in the file is only 80bytes.

**Review by misunmin — CHANGES_REQUESTED** [review]
line 826, a change needed as below, otherwise it prints twice.
  write (6,'(a,a80)') ' hdr:', hdr  --> if (ifverbose) write (6,'(a,a80)') ' hdr:', hdr

**Review by misunmin — CHANGES_REQUESTED** [review]
In coef.f, a change needed:

if (nid.eq.0) write(6,'(A,I10,A)') 
&        'Jac error 1 in ',kerr,' elements, setting p66=4, ifxyo=t'
--> if (nid.eq.0) write(6,*) 'Jac error 1, setting p66=4, ifxyo=t'

**Review by misunmin — APPROVED** [review]
Tested n2to3/n2to3co2 up to 2B elements and timestep runs up to 1B elements.

**Pull request merged**
