### PR TITLE
Deleted axi.rea, included axi.box in short_tests

### PR DESCRIPTION
**Pull request by RonRahaman**
In NekTests.py, both genbox and genmap are run. Previously, genbox failed because axi.box wasn't present. However, the whole test succeeded because axi.rea was already present.

Now, axi.rea is generated when genbox is run. This should provide a better test for genbox.

### CODE REVIEW

**Comment by RonRahaman** [comment]
Looks like the axi tests fail because axi.rea is formatted incorrectly.  At runtime, I get the error:

```
At line 219 of file /home/travis/build/Nek5000/Nek5000/core/connect2.f (unit = 9, file = '/home/travis/build/Nek5000/Nek5000/short_tests/axi/axi.rea')
Fortran runtime error: End of file
```

**Comment by stgeke** [comment]
You get this error because there is no .rea file. 
Is this a change to develop or to v.16.0.0?

**Comment by RonRahaman** [comment]
Ah, yes, looks like genbox isn't running to completion.  It generates this error:

```
Running "genbox"...
    Using command "/home/travis/build/Nek5000/Nek5000/bin/genbox"
    Using stdin "['axi.box']"
    Using working directory "/home/travis/build/Nek5000/Nek5000/short_tests/axi"
 input file name:
axisymmetric.rea
At line 137 of file genbox.f (unit = 8, file = 'ï¿½ï¿½E')
Fortran runtime error: File 'axisymmetric.rea' does not exist
```

Seems like I need to add axisymmetric.rea to the short_tests directory?

**Comment by stgeke** [comment]
Yes, genbox is looking for a .rea template. This PR make no sense to me as we do not need/want to run genbox for all short_tests.

**Comment by RonRahaman** [comment]
The 'axi' test case is the only one in short_tests that runs genbox.  I'm not sure why it was decided that axi should run genbox.  It was done in the legacy test suite, and I simply replicated the functionality.  

Would you like to omit the genbox run from the axi test case?  If so, should we omit axi.box and include axi.rea in short_tests/axi?

**Comment by stgeke** [comment]
Yes, let's have .rea file instead of running genbox. Do you want to open up an enhancement issue to add tests for tools?

**Comment by RonRahaman** [comment]
Issue added, see #66

**Comment by fischer1** [comment]
Are we good to go on this?

**Comment by fischer1** [comment]
@ananiast  can you take care of this ?

**Comment by fischer1** [comment]
@RonRahaman 

Hi Ron,

What's the status with this issue .. ? Do things work now for this case?  Should I merge?

**Pull request closed without merging**
