### PR TITLE
Why full restart requires 4 files (Issue 23)

### PR DESCRIPTION
**Pull request by EvelynOtero**
The pressure for nbd=2 was not saved, needed for extrapolation at nbd=3.

### CODE REVIEW

**Comment by stgeke** [comment]
Why is this pull request related to issue-23?

**Comment by EvelynOtero** [comment]
Only the last commit should be taken into account (9468008). This correction solves the issue of the full restart which now needs only 3 files. 
The 4th file was actually necessary because of the error introduced at the 3rd iteration with wrong pressure extrapolation. The pressure for the 2nd iteration or nbd=2 was not saved.

**Comment by stgeke** [comment]
Please include _only_ the relevant changes.

**Comment by EvelynOtero** [comment]
Yes, you are right. Something went wrong sorry. And I still need to figure out what it was, since this was not my intention.

**Comment by EvelynOtero** [comment]
Let me know please if you want me to do something else.

**Comment by maxhutch** [comment]
@EvelynOtero Great catch!  This will make life much better.

**Comment by EvelynOtero** [comment]
@maxhutch Thanks! And nice to hear that.

**Comment by stgeke** [comment]
@EvelynOtero Please close this PR and open up a new one containing the relevant commit merged into the latest v16.0.0 branch.

**Pull request closed without merging**
