### PR TITLE
Major viscous update and BC correction

### PR DESCRIPTION
**Pull request by hackljf**
This is is the first shock-capturing version of CMT-nek. Shock-capturing cases demonstrating this will be forthcoming (at least in NekExamples). Separate stress tensors for the compressible Navier-Stokes equations as well as Guermond & Popov's 2014 viscous regularization of the Euler equations side-by-side. BC are also improved (except subsonic inflow).

### CODE REVIEW

**Comment by RonRahaman** [comment]
Travis crashed because a "pip install" was interrupted.  Not the fault of this PR.  Probably just an issue on the Travis servers.  I am restarted the failed  build manually.

**Comment by hackljf** [comment]
Thank you, Ron.

**Comment by stgeke** [comment]
Is the DOXYFILE really needed?

**Comment by RonRahaman** [comment]
@hackljf did the folks at UFCCMT write that Doxyfile?  

We should definitely start generating doxygen again (I've numerous requests), and I do have an old Doxyfile for Nek (not in the repo, just on my hard drive).  If you're interested in merging changes from the Doxyfile with mine, maybe we can do it another PR.

**Comment by stgeke** [comment]
We are working on a online code documentation system based on Doxygen. The guys at KTH want to come up with a suggestion how to do it.

**Comment by hackljf** [comment]
Yes I wrote it and added it. No, it is not really needed. I don't know much
Doxygen, but I have done enough with it to convince myself that it would be
useful going forward. I could see divorcing the doxyfile from the actual
source repository, however.

**Comment by stgeke** [comment]
Let's add when we are ready. 

 
 
-----Original message-----

**Comment by hackljf** [comment]
ok. do I need to remove it and update the PR?

**Comment by hackljf** [comment]
Doxyfile has been removed. Is there anything else I need to do?

**Comment by hackljf** [comment]
changed checkpointing and (finally) allow variable time step.

**Comment by hackljf** [comment]
I'm going to need someone to restart travis again. This time it failed (re-?)installing mpich on the remote host for testing.

**Comment by RonRahaman** [comment]
@hackljf, I just restarted Travis for the failed build.

**Comment by hackljf** [comment]
Thanks

**Pull request merged**
