### PR TITLE
Revert "Cray patch"

### PR DESCRIPTION
**Pull request by maxhutch**
Reverts Nek5000/Nek5000#19

These aren't passing the buildbot tests.

CC: @nicooff @RonRahaman

### CODE REVIEW

**Comment by RonRahaman** [comment]
Thanks, Max.  We'll revert this until we figure out what the issue is.

**Comment by pschlatt1** [comment]
I will look at it these days. Thanks to buildbot for telling us!

**Comment by maxhutch** [comment]
@RonRahaman , did you mean to merge this?

**Comment by RonRahaman** [comment]
Yes, I forgot to click the button :)

**Comment by nicooff** [comment]
@maxhutch @RonRahaman 
Probably a newbie question here but where can I get access to the buildbot results with the list of tests that passed and failed?

**Pull request merged**
