### PR TITLE
planar averaging with gs_op

### PR DESCRIPTION
**Pull request by kmittal2**
Routine for planar averaging with gs_op in x/y/z direction for box type meshes.

### CODE REVIEW

**Comment by stgeke** [comment]
Will this work for pressure and PnPn2? 
How about making it more generic i.e. support other gs operations like min/max?

**Comment by kmittal2** [comment]
For pressure in PnPn2, I think it will be better if the user maps the pr to pm1 and then send it to this routine. Or we could add another input to the routine which determines if the input variable needs to be mapped to mesh1 or not.
I will add support for other gs operations (min and max should suffice I think).

**Comment by stgeke** [comment]
I'll wait for #399 to be ready. Both should provide a similar API.

**Comment by kmittal2** [comment]
I don't think we really need ifld here.. my intention for ifld was to allow user to let the user average across just fluid elements, or across fluid and solid elements.. however I just realized that if we consider that we number fluid elements first, for cases where nelt > nelv, the global numbering used to setup gs_hndl won't be consistent to allow users to average a variable across fluid and solid elements.

**Comment by stgeke** [comment]
Replaced by #481

**Pull request closed without merging**
