### PR TITLE
Fix issue-105

### PR DESCRIPTION
**Pull request by nicooff**
Issue 105 relates to conflicts in variables name.

Issue is fixed by changing the variables name in the include files GMRES, SEMHAT and ORTHO{P,V,T,STRS}.

An example where all include files are included will be added shortly in the repo NekExamples in order to test the present pull request.

### CODE REVIEW

**Comment by RonRahaman** [comment]
@nicooff, should this be reopened?

**Comment by nicooff** [comment]
@RonRahaman No, I had to close it because I made a wrong manipulation but the issue has been fixed by pull request #107 .

**Comment by RonRahaman** [comment]
Great, just wanted to be sure we weren't ignoring your PRs.  The incl_def test is now being run in Jenkins, so I think you should be set.

**Comment by nicooff** [comment]
Awesome! Thank you.

**Pull request closed without merging**
