### PR TITLE
Cvode Travis tests

### PR DESCRIPTION
**Pull request by RonRahaman**
Travis now does the following:

* Conditionally installs CVODE for only the tests that need it
* Uses the script in 3rd_party/cvode/ to install CVODE
* Installs the CVODE headers/libraries in 3rd_party/cvode/

### CODE REVIEW

**Comment by stgeke** [comment]
It looks the tools do not compile correctly. Somehow we pass `false` as an argument. I guess I messed something up. Also, makenek clean requires a user input (see below) now. Looks like we have to account for this in our scripts. 

----------------------
Make genmap...
----------------------
make[1]: Entering directory `/home/travis/build/Nek5000/Nek5000/tools/genmap'
gfortran -c -cpp false -fdefault-real-8 genmap.f
gfortran: error: false: No such file or directory
make[1]: *** [genmap.o] Error 1
make[1]: Leaving directory `/home/travis/build/Nek5000/Nek5000/tools/genmap'
make: *** [all] Error 1
Successfully compiled tools!
Running "genmap"...
    Using command "/home/travis/build/Nek5000/Nek5000/bin/genmap"
    Using stdin "['eddy_uv', '0.5']"
    Using working directory "/home/travis/build/Nek5000/Nek5000/short_tests/eddy"
Could not complete /home/travis/build/Nek5000/Nek5000/bin/genmap!  Caught error: "[Errno 2] No such file or directory".  Check "/home/travis/build/Nek5000/Nek5000/short_tests/eddy/genmap.out" for details.
Compiling nek5000...
    Using source directory "/home/travis/build/Nek5000/Nek5000"
    Using working directory "/home/travis/build/Nek5000/Nek5000/short_tests/eddy"
    Using .usr file "eddy_uv"
    Using USR_LFLAGS=""
    Using SOURCE_ROOT="/home/travis/build/Nek5000/Nek5000"
    Using CFLAGS=""
    Using CC="gcc"
    Using FFLAGS=""
    Using F77="gfortran"
    Using PPLIST=""
    Using MPI="0"
makenek - automatic build tool for Nek5000
Clean all 3rd party code? [N]

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated

**Comment by RonRahaman** [comment]
Ok, I'll try running NekTests locally and see what happens

**Comment by RonRahaman** [comment]
The last two commits were some fixes to NekTests.py, regarding the issues you mentioned.  

* Previously, NekTests.py did a find/replace to set the value of the BIGMEM variable in maketools.  In previous versions of Nek, BIGMEM was set by the user, so the NekTest.py's  behavior made sense.  However, as of be07005fe36a90fde4d497dbe0b294c57fdd4a00, BIGMEM is not meant to be touched, so NekTest.py's behavior caused errors.  This is now fixed.

* NekTests.py passes stdin to makenek, as required.  It just passes a newline byte, which is what is required.

**Comment by stgeke** [comment]
Thanks a lot @RonRahaman !

**Pull request merged**
